package com.troublesometrio.spncraft.Client.models.impala;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelImpala extends ModelBase
{
    ModelRenderer rightBackWheel;
    ModelRenderer rightFrontWheel;
    ModelRenderer leftFrontWheel;
    ModelRenderer leftBackWheel;
    ModelRenderer front;
    ModelRenderer bottom;
    ModelRenderer top;
    ModelRenderer rightBackSeat1;
    ModelRenderer rightBackSeat2;
    ModelRenderer leftBackSeat1;
    ModelRenderer leftBackSeat2;
    ModelRenderer leftFrontSeat1;
    ModelRenderer leftFrontSeat2;
    ModelRenderer rightFrontSeat1;
    ModelRenderer rightFrontSeat2;
    ModelRenderer backWindow;
    ModelRenderer frontWindow;
    ModelRenderer leftSide1;
    ModelRenderer leftSide2;
    ModelRenderer leftSide3;
    ModelRenderer leftSide4;
    ModelRenderer leftSide5;
    ModelRenderer rightSide1;
    ModelRenderer rightSide2;
    ModelRenderer rightSide3;
    ModelRenderer rightSide4;
    ModelRenderer rightSide5;
    ModelRenderer steeringWheel;
    ModelRenderer leftBackDoor;
    ModelRenderer rightBackDoor;
    ModelRenderer leftFrontDoor;
    ModelRenderer rightFrontDoor;
    ModelRenderer leftBackLight;
    ModelRenderer rightBackLight;
    ModelRenderer trunk1;
    ModelRenderer trunk2;
    ModelRenderer back1;
    ModelRenderer back2;
  
  public ModelImpala()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      rightBackWheel = new ModelRenderer(this, 130, 0);
      rightBackWheel.addBox(-2F, -5F, -5F, 4, 10, 10);
      rightBackWheel.setRotationPoint(-14.1F, 19F, 30F);
      rightBackWheel.setTextureSize(512, 256);
      rightBackWheel.mirror = true;
      setRotation(rightBackWheel, 0F, 0F, 0F);
      rightFrontWheel = new ModelRenderer(this, 130, 0);
      rightFrontWheel.addBox(-2F, -5F, -5F, 4, 10, 10);
      rightFrontWheel.setRotationPoint(-14.1F, 19F, -21F);
      rightFrontWheel.setTextureSize(512, 256);
      rightFrontWheel.mirror = true;
      setRotation(rightFrontWheel, 0F, 0F, 0F);
      leftFrontWheel = new ModelRenderer(this, 130, 0);
      leftFrontWheel.addBox(-2F, -5F, -5F, 4, 10, 10);
      leftFrontWheel.setRotationPoint(14.1F, 19F, -21F);
      leftFrontWheel.setTextureSize(512, 256);
      leftFrontWheel.mirror = true;
      setRotation(leftFrontWheel, 0F, 0F, 0F);
      leftBackWheel = new ModelRenderer(this, 130, 0);
      leftBackWheel.addBox(-2F, -5F, -5F, 4, 10, 10);
      leftBackWheel.setRotationPoint(14.1F, 19F, 30F);
      leftBackWheel.setTextureSize(512, 256);
      leftBackWheel.mirror = true;
      setRotation(leftBackWheel, 0F, 0F, 0F);
      front = new ModelRenderer(this, 0, 0);
      front.addBox(-16F, 0F, -29F, 32, 12, 29);
      front.setRotationPoint(0F, 8F, -12F);
      front.setTextureSize(512, 256);
      front.mirror = true;
      setRotation(front, 0F, 0F, 0F);
      bottom = new ModelRenderer(this, 0, 45);
      bottom.addBox(-16F, 0F, -9F, 32, 1, 38);
      bottom.setRotationPoint(0F, 19F, -3F);
      bottom.setTextureSize(512, 256);
      bottom.mirror = true;
      setRotation(bottom, 0F, 0F, 0F);
      top = new ModelRenderer(this, 0, 90);
      top.addBox(-16F, 0F, -15F, 32, 1, 44);
      top.setRotationPoint(0F, -5F, 0F);
      top.setTextureSize(512, 256);
      top.mirror = true;
      setRotation(top, 0F, 0F, 0F);
      rightBackSeat1 = new ModelRenderer(this, 166, 0);
      rightBackSeat1.addBox(-7F, -7F, -3F, 11, 6, 10);
      rightBackSeat1.setRotationPoint(-6F, 19F, 16F);
      rightBackSeat1.setTextureSize(512, 256);
      rightBackSeat1.mirror = true;
      setRotation(rightBackSeat1, 0F, 0F, 0F);
      rightBackSeat2 = new ModelRenderer(this, 212, 0);
      rightBackSeat2.addBox(-7F, -16F, 7F, 11, 16, 1);
      rightBackSeat2.setRotationPoint(-6F, 19F, 16F);
      rightBackSeat2.setTextureSize(512, 256);
      rightBackSeat2.mirror = true;
      setRotation(rightBackSeat2, 0F, 0F, 0F);
      leftBackSeat1 = new ModelRenderer(this, 166, 0);
      leftBackSeat1.addBox(-7F, -7F, -3F, 11, 6, 10);
      leftBackSeat1.setRotationPoint(9F, 19F, 16F);
      leftBackSeat1.setTextureSize(512, 256);
      leftBackSeat1.mirror = true;
      setRotation(leftBackSeat1, 0F, 0F, 0F);
      leftBackSeat2 = new ModelRenderer(this, 212, 0);
      leftBackSeat2.addBox(-7F, -16F, 7F, 11, 16, 1);
      leftBackSeat2.setRotationPoint(9F, 19F, 16F);
      leftBackSeat2.setTextureSize(512, 256);
      leftBackSeat2.mirror = true;
      setRotation(leftBackSeat2, 0F, 0F, 0F);
      leftFrontSeat1 = new ModelRenderer(this, 166, 0);
      leftFrontSeat1.addBox(-7F, -7F, -3F, 11, 6, 10);
      leftFrontSeat1.setRotationPoint(9F, 19F, -1F);
      leftFrontSeat1.setTextureSize(512, 256);
      leftFrontSeat1.mirror = true;
      setRotation(leftFrontSeat1, 0F, 0F, 0F);
      leftFrontSeat2 = new ModelRenderer(this, 212, 0);
      leftFrontSeat2.addBox(-7F, -16F, 7F, 11, 16, 1);
      leftFrontSeat2.setRotationPoint(9F, 19F, -1F);
      leftFrontSeat2.setTextureSize(512, 256);
      leftFrontSeat2.mirror = true;
      setRotation(leftFrontSeat2, 0F, 0F, 0F);
      rightFrontSeat1 = new ModelRenderer(this, 166, 0);
      rightFrontSeat1.addBox(-7F, -7F, -3F, 11, 6, 10);
      rightFrontSeat1.setRotationPoint(-6F, 19F, -1F);
      rightFrontSeat1.setTextureSize(512, 256);
      rightFrontSeat1.mirror = true;
      setRotation(rightFrontSeat1, 0F, 0F, 0F);
      rightFrontSeat2 = new ModelRenderer(this, 212, 0);
      rightFrontSeat2.addBox(-7F, -16F, 7F, 11, 16, 1);
      rightFrontSeat2.setRotationPoint(-6F, 19F, -1F);
      rightFrontSeat2.setTextureSize(512, 256);
      rightFrontSeat2.mirror = true;
      setRotation(rightFrontSeat2, 0F, 0F, 0F);
      backWindow = new ModelRenderer(this, 240, 0);
      backWindow.addBox(-16F, -5F, 0F, 32, 12, 1);
      backWindow.setRotationPoint(0F, 1F, 28F);
      backWindow.setTextureSize(512, 256);
      backWindow.mirror = true;
      setRotation(backWindow, 0F, 0F, 0F);
      frontWindow = new ModelRenderer(this, 309, 0);
      frontWindow.addBox(-16F, -5F, 0F, 32, 12, 1);
      frontWindow.setRotationPoint(0F, 1F, -15F);
      frontWindow.setTextureSize(512, 256);
      frontWindow.mirror = true;
      setRotation(frontWindow, 0F, 0F, 0F);
      leftSide1 = new ModelRenderer(this, 129, 25);
      leftSide1.addBox(0F, -11F, -12F, 1, 12, 2);
      leftSide1.setRotationPoint(15F, 7F, -2F);
      leftSide1.setTextureSize(512, 256);
      leftSide1.mirror = true;
      setRotation(leftSide1, 0F, 0F, 0F);
      leftSide2 = new ModelRenderer(this, 141, 25);
      leftSide2.addBox(0F, -11F, -12F, 1, 23, 7);
      leftSide2.setRotationPoint(15F, 7F, 0F);
      leftSide2.setTextureSize(512, 256);
      leftSide2.mirror = true;
      setRotation(leftSide2, 0F, 0F, 0F);
      leftSide3 = new ModelRenderer(this, 160, 25);
      leftSide3.addBox(0F, -11F, 20F, 1, 23, 6);
      leftSide3.setRotationPoint(15F, 7F, 0F);
      leftSide3.setTextureSize(512, 256);
      leftSide3.mirror = true;
      setRotation(leftSide3, 0F, 0F, 0F);
      leftSide4 = new ModelRenderer(this, 176, 25);
      leftSide4.addBox(0F, -11F, 28F, 1, 12, 2);
      leftSide4.setRotationPoint(15F, 7F, -2F);
      leftSide4.setTextureSize(512, 256);
      leftSide4.mirror = true;
      setRotation(leftSide4, 0F, 0F, 0F);
      leftSide5 = new ModelRenderer(this, 184, 25);
      leftSide5.addBox(15F, 0F, 12F, 1, 6, 12);
      leftSide5.setRotationPoint(0F, 8F, 26F);
      leftSide5.setTextureSize(512, 256);
      leftSide5.mirror = true;
      setRotation(leftSide5, 0F, 0F, 0F);
      rightSide1 = new ModelRenderer(this, 220, 25);
      rightSide1.addBox(0F, -11F, -12F, 1, 12, 2);
      rightSide1.setRotationPoint(-16F, 7F, -2F);
      rightSide1.setTextureSize(512, 256);
      rightSide1.mirror = true;
      setRotation(rightSide1, 0F, 0F, 0F);
      rightSide2 = new ModelRenderer(this, 230, 25);
      rightSide2.addBox(0F, -11F, -12F, 1, 23, 7);
      rightSide2.setRotationPoint(-16F, 7F, 0F);
      rightSide2.setTextureSize(512, 256);
      rightSide2.mirror = true;
      setRotation(rightSide2, 0F, 0F, 0F);
      rightSide3 = new ModelRenderer(this, 248, 25);
      rightSide3.addBox(0F, -11F, 20F, 1, 23, 6);
      rightSide3.setRotationPoint(-16F, 7F, 0F);
      rightSide3.setTextureSize(512, 256);
      rightSide3.mirror = true;
      setRotation(rightSide3, 0F, 0F, 0F);
      rightSide4 = new ModelRenderer(this, 264, 25);
      rightSide4.addBox(0F, -11F, 28F, 1, 12, 2);
      rightSide4.setRotationPoint(-16F, 7F, -2F);
      rightSide4.setTextureSize(512, 256);
      rightSide4.mirror = true;
      setRotation(rightSide4, 0F, 0F, 0F);
      rightSide5 = new ModelRenderer(this, 272, 25);
      rightSide5.addBox(-16F, 0F, 12F, 1, 6, 12);
      rightSide5.setRotationPoint(0F, 8F, 26F);
      rightSide5.setTextureSize(512, 256);
      rightSide5.mirror = true;
      setRotation(rightSide5, 0F, 0F, 0F);
      steeringWheel = new ModelRenderer(this, 140, 56);
      steeringWheel.addBox(-5F, -5F, 0F, 10, 10, 1);
      steeringWheel.setRotationPoint(9F, 8F, -12F);
      steeringWheel.setTextureSize(512, 256);
      steeringWheel.mirror = true;
      setRotation(steeringWheel, 0.2617994F, 0F, 0F);
      leftBackDoor = new ModelRenderer(this, 0, 140);
      leftBackDoor.addBox(0F, -11F, 0F, 1, 23, 13);
      leftBackDoor.setRotationPoint(15F, 7F, 7F);
      leftBackDoor.setTextureSize(512, 256);
      leftBackDoor.mirror = true;
      setRotation(leftBackDoor, 0F, 0F, 0F);
      rightBackDoor = new ModelRenderer(this, 30, 140);
      rightBackDoor.addBox(0F, -11F, 0F, 1, 23, 13);
      rightBackDoor.setRotationPoint(-16F, 7F, 7F);
      rightBackDoor.setTextureSize(512, 256);
      rightBackDoor.mirror = true;
      setRotation(rightBackDoor, 0F, 0F, 0F);
      leftFrontDoor = new ModelRenderer(this, 60, 140);
      leftFrontDoor.addBox(0F, -11F, 0F, 1, 23, 13);
      leftFrontDoor.setRotationPoint(15F, 7F, -6F);
      leftFrontDoor.setTextureSize(512, 256);
      leftFrontDoor.mirror = true;
      setRotation(leftFrontDoor, 0F, 0F, 0F);
      rightFrontDoor = new ModelRenderer(this, 90, 140);
      rightFrontDoor.addBox(0F, -11F, 0F, 1, 23, 13);
      rightFrontDoor.setRotationPoint(-16F, 7F, -6F);
      rightFrontDoor.setTextureSize(512, 256);
      rightFrontDoor.mirror = true;
      setRotation(rightFrontDoor, 0F, 0F, 0F);
      leftBackLight = new ModelRenderer(this, 390, 0);
      leftBackLight.addBox(11F, 0F, 23F, 4, 6, 1);
      leftBackLight.setRotationPoint(0F, 8F, 26F);
      leftBackLight.setTextureSize(512, 256);
      leftBackLight.mirror = true;
      setRotation(leftBackLight, 0F, 0F, 0F);
      rightBackLight = new ModelRenderer(this, 390, 0);
      rightBackLight.addBox(-15F, 0F, 23F, 4, 6, 1);
      rightBackLight.setRotationPoint(0F, 8F, 26F);
      rightBackLight.setTextureSize(512, 256);
      rightBackLight.mirror = true;
      setRotation(rightBackLight, 0F, 0F, 0F);
      trunk1 = new ModelRenderer(this, 200, 64);
      trunk1.addBox(-15F, 0F, 0F, 30, 1, 11);
      trunk1.setRotationPoint(0F, 8F, 38F);
      trunk1.setTextureSize(512, 256);
      trunk1.mirror = true;
      setRotation(trunk1, 0F, 0F, 0F);
      trunk2 = new ModelRenderer(this, 200, 79);
      trunk2.addBox(-11F, 0F, 11F, 22, 6, 1);
      trunk2.setRotationPoint(0F, 8F, 38F);
      trunk2.setTextureSize(512, 256);
      trunk2.mirror = true;
      setRotation(trunk2, 0F, 0F, 0F);
      back1 = new ModelRenderer(this, 300, 19);
      back1.addBox(-16F, 0F, 0F, 32, 12, 12);
      back1.setRotationPoint(0F, 8F, 26F);
      back1.setTextureSize(512, 256);
      back1.mirror = true;
      setRotation(back1, 0F, 0F, 0F);
      back2 = new ModelRenderer(this, 300, 46);
      back2.addBox(-16F, 6F, 12F, 32, 6, 12);
      back2.setRotationPoint(0F, 8F, 26F);
      back2.setTextureSize(512, 256);
      back2.mirror = true;
      setRotation(back2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    rightBackWheel.render(f5);
    rightFrontWheel.render(f5);
    leftFrontWheel.render(f5);
    leftBackWheel.render(f5);
    front.render(f5);
    bottom.render(f5);
    top.render(f5);
    rightBackSeat1.render(f5);
    rightBackSeat2.render(f5);
    leftBackSeat1.render(f5);
    leftBackSeat2.render(f5);
    leftFrontSeat1.render(f5);
    leftFrontSeat2.render(f5);
    rightFrontSeat1.render(f5);
    rightFrontSeat2.render(f5);
    backWindow.render(f5);
    frontWindow.render(f5);
    leftSide1.render(f5);
    leftSide2.render(f5);
    leftSide3.render(f5);
    leftSide4.render(f5);
    leftSide5.render(f5);
    rightSide1.render(f5);
    rightSide2.render(f5);
    rightSide3.render(f5);
    rightSide4.render(f5);
    rightSide5.render(f5);
    steeringWheel.render(f5);
    leftBackDoor.render(f5);
    rightBackDoor.render(f5);
    leftFrontDoor.render(f5);
    rightFrontDoor.render(f5);
    leftBackLight.render(f5);
    rightBackLight.render(f5);
    trunk1.render(f5);
    trunk2.render(f5);
    back1.render(f5);
    back2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
